const projects = [
  {
    id: 1,
    image: "/images/porto/codedev.png",
    title: "PCodeDev",
    description: "An e-commerce site for Jas Akoding services and products.",
    type: "Website",
    link: "https://codedev-app.vercel.app/",
  },
  {
    id: 2,
    image: "/images/porto/maggot.png",
    title: "MAGGOT BSF COLOMADU",
    description: "A simple company profile for maggot farming.",
    type: "Web Application",
    link: "https://maggotbsfcolomadu.vercel.app/",
  },
  {
    id: 3,
    image: "/images/porto/dompet.png",
    title: "KasirPintar",
    description: "An app to record and manage financial data.",
    type: "Mobile App",
    link: "https://github.com/johannesdebritto/Dompetku",
  },
  {
    id: 4,
    image: "/images/porto/map.png",
    title: "SmartMap",
    description: "A web-based azimuth tracking tool.",
    type: "Mobile App",
    link: "https://github.com/johannesdebritto/AZIMUTHTRACKER",
  },
  {
    id: 5,
    image: "/images/porto/scan.png",
    title: "QR Scanner",
    description: "A mobile app to scan items at events.",
    type: "Mobile App",
    link: "https://github.com/johannesdebritto/ScanBarang_Frontend",
  },
  {
    id: 6,
    image: "/images/porto/sehat.png",
    title: "SehatNow",
    description: "An app for buying and ordering medicine.",
    type: "Mobile App",
    link: "https://github.com/johannesdebritto/TubesMobilePrograming_JUNIORCARE",
  },
  {
    id: 7,
    image: "/images/porto/konimexxx.png",
    title: "Konimex Monitoring",
    description: "An application for monitoring PT KONIMEX buildings using RFID and NFC scanning.",
    type: "Mobile App",
    link: "#", // Ganti dengan link yang sesuai jika ada
  },
];
